#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# Bloquear push directo a main/master
if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  echo "🚫 No se permite push directo a $BRANCH. Crea un PR."
  exit 1
fi